CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Wallets" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DocumentId" varchar(20) NOT NULL,
    "DocumentType" text NOT NULL,
    "Name" varchar(120) NOT NULL,
    "Balance" numeric(18,2) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Wallets" PRIMARY KEY ("Id")
);

CREATE TABLE "Movements" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "WalletId" int NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "Type" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Movements" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Movements_Wallets_WalletId" FOREIGN KEY ("WalletId") REFERENCES "Wallets" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Movements_WalletId" ON "Movements" ("WalletId");

CREATE INDEX "IX_Movements_WalletId_CreatedAt" ON "Movements" ("WalletId", "CreatedAt");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250509094019_InitialMigration', '8.0.10');

COMMIT;

START TRANSACTION;

ALTER TABLE "Movements" DROP CONSTRAINT "FK_Movements_Wallets_WalletId";

ALTER TABLE "Wallets" ALTER COLUMN "Name" TYPE character varying(100);

ALTER TABLE "Wallets" ALTER COLUMN "DocumentId" TYPE character varying(100);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250509110832_RemoveRelationsMigration', '8.0.10');

COMMIT;

